<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>S4HERP.Finance.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../S4HERP.Finance.Application/S4HERP.Finance.Application.csproj" />
  </ItemGroup>

</Project>
